FROM node:12.18.4 as dist
LABEL maintainer="simon@torrentofshame.com"

RUN mkdir -p /home/frontend/app
WORKDIR /home/frontend/app

COPY package*.json ./

RUN npm ci

COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=dist /home/frontend/app/dist /usr/share/nginx/html
COPY nginx.dev.conf /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]
