version: "3"
services:
  frontend:
    container_name: frontend
    image: torrentofshame/frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
      
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
  
  backend:
    restart: always
    depends_on:
      - mongo
    container_name: backend
    image: torrentofshame/backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - MONGO_URI=mongodb://mongo/
      - APP_SETTINGS=server.config.ProductionConfig
      
volumes:
    mongo-data:
