version: "3"
services:
  #frontend:
    #container_name: frontend
    #image: torrentofshame/frontend
    #build:
      #context: ./frontend
      #dockerfile: Dockerfile.dev
    #ports:
      #- "127.0.0.1:3000:80"
    #volumes:
      #- ./frontend:/home/frontend/app
      
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
  
  backend:
    restart: always
    depends_on:
      - mongo
    container_name: backend
    image: torrentofshame/backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/home/backend/app
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      FLASK_ENV: development
      MONGO_URI: "mongodb://mongo/backendtest"
      FLASK_DEBUG: 1
      APP_SETTINGS: server.config.DevelopmentConfig
      
volumes:
  mongo-data:
