version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:80
      
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
  
  backend:
    restart: always
    depends_on:
      - mongo
    container_name: backend
    build: ./backend
    expose:
      - 5000
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - MONGO_URI=mongodb://mongo/
      - FLASK_DEBUG=1
      - APP_SETTINGS=server.config.DevelopmentConfig
      
  volumes:
    mongo-data
